language: node_js
node_js:
  - "stable"
install:
  - npm i
cache:
  directories:
    - node_modules
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS tax24;'
  - npm run db:rollback
  - npm run db:migrate
  - npm run db:seed
script:
  - npm test
after_success:
  - npm run coverage
branches:
  only:
    - master
    - dev
deploy:
  provider: heroku
  api_key:
    secure: ADD_API_KEY_HERE
  app:
    master: tax24
    dev: tax24-staging